import pytz

from datetime import timedelta

from dateutil.relativedelta import relativedelta

from odoo import _, api, fields, models
from odoo.exceptions import UserError

from ..const import SEAT_HOLDING_STATES

# How far ahead the cron materialises departures.
HORIZON_MONTHS = 12

# Context flag marking a write as the module's own machinery rather than a
# person. Only writes *without* it count as manual adjustments; see `write`.
SYSTEM_WRITE = "tour_system_write"

# The widest span the booking calendar will draw in one call.
#
# `get_calendar_grid` is reachable by RPC and used to read whatever range it was
# handed: eleven years took 411ms and thirty-one queries against eighteen
# thousand departures, on one worker, for one mistyped request. The component
# asks for a week, or a single day; six weeks leaves room for a month view to be
# added without anybody having to remember this number exists.
MAX_GRID_DAYS = 42


class TourDeparture(models.Model):
    """A dated instance of a tour, and the thing that actually holds seats.

    This is where the module differs from an accommodation booking engine, and
    everything else follows from it. A room is exclusive: it is occupied or it
    is not, so occupancy is a boolean over a date range. A departure is shared:
    one 09:00 boat with capacity 15 carries six unrelated bookings totalling 15
    people. Availability is `capacity - seats_sold`, an inventory drawn down,
    never a resource that gets blocked.
    """

    _name = "tour.departure"
    _description = "Scheduled Trip"
    _order = "start_datetime, id"

    tour_id = fields.Many2one("tour.tour", required=True, ondelete="cascade", index=True)
    rule_id = fields.Many2one(
        "tour.availability.rule",
        string="Generated By",
        ondelete="set null",
        index=True,
        help="The rule that created this departure. Cleared rather than "
             "cascaded when the rule is deleted: dropping a schedule must "
             "never delete departures people have booked.",
    )
    company_id = fields.Many2one(related="tour_id.company_id", store=True)
    currency_id = fields.Many2one(related="tour_id.currency_id")

    date = fields.Date(required=True, index=True)
    start_datetime = fields.Datetime(required=True, index=True)
    capacity = fields.Integer(required=True)
    min_pax = fields.Integer(string="Minimum Party Size", required=True, default=1)
    max_pax = fields.Integer(string="Maximum Party Size", required=True, default=10)

    seats_sold = fields.Integer(compute="_compute_seats", store=True)
    seats_available = fields.Integer(compute="_compute_seats", store=True)

    state = fields.Selection(
        [
            ("draft", "Draft"),
            ("open", "Open"),
            ("full", "Full"),
            ("cancelled", "Cancelled"),
            ("done", "Done"),
        ],
        required=True,
        default="open",
        index=True,
    )
    is_manually_adjusted = fields.Boolean(
        string="Manually Adjusted",
        help="Set when someone changes this departure by hand. The generator "
             "leaves such departures alone for good.",
    )
    booking_ids = fields.One2many("tour.booking", "departure_id")

    _unique_slot = models.Constraint(
        "UNIQUE(tour_id, start_datetime)",
        "That tour already has a departure at that moment.",
    )

    @api.depends("capacity", "booking_ids.state", "booking_ids.pax")
    def _compute_seats(self):
        held = self.env["tour.booking"]._read_group(
            [
                ("departure_id", "in", self.ids),
                ("state", "in", SEAT_HOLDING_STATES),
            ],
            ["departure_id"],
            ["pax:sum"],
        )
        sold = {departure.id: total for departure, total in held}
        for departure in self:
            departure.seats_sold = sold.get(departure.id, 0)
            departure.seats_available = max(0, departure.capacity - departure.seats_sold)

    def _sync_full_state(self):
        """Keep `open` and `full` in step with the seat count.

        Deliberately not done inside `_compute_seats`. Assigning a non-computed
        field from a compute goes through the full `write()` path, which would
        trip the manual-adjustment flag below every time somebody booked a seat,
        and quietly exempt the departure from ever being retired again.

        `cancelled` and `done` are decisions, not bookkeeping: selling or
        releasing a seat must never overrule one.
        """
        for departure in self:
            if departure.state not in ("open", "full"):
                continue
            target = "full" if departure.seats_available <= 0 else "open"
            if departure.state != target:
                departure.with_context(**{SYSTEM_WRITE: True}).state = target

    def _local_start(self):
        """The departure time in the tour's own timezone. -> aware datetime.

        Not `context_timestamp`, which converts to whoever happens to be
        looking. A 09:00 dive on Bonaire is at 09:00 for the guest standing on
        the dock, and telling them 13:00 because the server runs in UTC — or
        because they are browsing from Amsterdam — is how people miss boats.
        """
        self.ensure_one()
        tz = pytz.timezone(self.tour_id.tz or "UTC")
        return pytz.utc.localize(self.start_datetime).astimezone(tz)

    @api.depends("tour_id.name", "start_datetime")
    def _compute_display_name(self):
        for departure in self:
            when = departure._local_start()
            if departure.tour_id.has_specific_time:
                label = when.strftime("%Y-%m-%d %H:%M")
            else:
                label = when.strftime("%Y-%m-%d")
            departure.display_name = "%s — %s" % (departure.tour_id.name, label)

    # --- The booking calendar ----------------------------------------------

    @api.model
    def get_calendar_grid(self, date_from, date_to, mode="time", show="all"):
        """The week grid behind the Booking Calendar. -> dict.

        Public on purpose: Odoo refuses RPC to any method whose name starts with
        an underscore, and the OWL component calls this one straight from the
        browser.

        Rows are start times and columns are days, which is how an operator
        reads a week: "what leaves at 09:00, and is Friday filling up?". Odoo's
        stock calendar cannot express that — it lays events out along a time
        axis — so the shape is computed here and drawn by an OWL component.

        All of it is one query and one pass. The alternative, letting the client
        ask per cell, would be forty-odd round trips for a single week.

        `mode` picks what the rows mean: `time` groups by departure time,
        `experience` groups by tour. `show` filters to `booked` or `disrupted`.
        """
        date_from = fields.Date.to_date(date_from)
        date_to = fields.Date.to_date(date_to)
        span = (date_to - date_from).days + 1
        if span < 1:
            raise UserError(_("The calendar cannot end before it starts."))
        if span > MAX_GRID_DAYS:
            raise UserError(_(
                "The calendar shows at most %(days)s days at a time, and "
                "%(asked)s were asked for.",
                days=MAX_GRID_DAYS,
                asked=span,
            ))

        departures = self.search([
            ("date", ">=", date_from),
            ("date", "<=", date_to),
        ], order="start_datetime")

        stats = {
            "departures": len(departures),
            "sold_out": len(departures.filtered(lambda d: d.state == "full")),
            "closed_out": len(departures.filtered(lambda d: d.state == "cancelled")),
            # A cancelled trip that people have already booked onto. Nothing
            # else on this screen is a problem the operator has to act on;
            # this one is, so it gets counted separately.
            "need_attention": len(departures.filtered(
                lambda d: d.state == "cancelled" and d.seats_sold > 0
            )),
        }

        if show == "booked":
            departures = departures.filtered(lambda d: d.seats_sold > 0)
        elif show == "disrupted":
            departures = departures.filtered(
                lambda d: d.state == "cancelled" or d.seats_sold > d.capacity
            )

        days = []
        day = date_from
        today = fields.Date.context_today(self)
        while day <= date_to:
            days.append({
                "date": day.isoformat(),
                "weekday": day.strftime("%a"),
                "day": day.day,
                "is_today": day == today,
            })
            day += timedelta(days=1)

        rows = {}
        for departure in departures:
            local = departure._local_start()
            if mode == "experience":
                key = "tour-%s" % departure.tour_id.id
                label = departure.tour_id.name
                sort = (departure.tour_id.sequence, departure.tour_id.name or "")
            else:
                key = local.strftime("%H:%M")
                label = key
                sort = (local.hour, local.minute)
            row = rows.setdefault(key, {"key": key, "label": label, "sort": sort, "cells": {}})
            row["cells"].setdefault(departure.date.isoformat(), []).append({
                "id": departure.id,
                "tour_id": departure.tour_id.id,
                "tour_name": departure.tour_id.name,
                "time": local.strftime("%H:%M"),
                "seats_sold": departure.seats_sold,
                "capacity": departure.capacity,
                "state": departure.state,
                # A stable colour per tour so a row reads as one thing across
                # the week. `color` lets the operator override it.
                "color": departure.tour_id.color or (departure.tour_id.id % 11),
                "has_time": departure.tour_id.has_specific_time,
            })

        return {
            "stats": stats,
            "days": days,
            "rows": [
                {k: v for k, v in row.items() if k != "sort"}
                for row in sorted(rows.values(), key=lambda r: r["sort"])
            ],
        }

    # --- Booking window ----------------------------------------------------

    def _cutoff_datetime(self):
        """The moment bookings stop being accepted. -> datetime."""
        self.ensure_one()
        return self.start_datetime - relativedelta(
            hours=self.tour_id.booking_cutoff_hours
        )

    def _is_bookable(self, now=None):
        """Can this departure still take a booking at all? -> bool."""
        self.ensure_one()
        now = now or fields.Datetime.now()
        return self.state in ("open", "full") and now < self._cutoff_datetime()

    # --- The seat guarantee ------------------------------------------------

    def _lock_and_check(self, pax, ignoring=None):
        """Take the row lock, then verify `pax` seats are genuinely free.

        The only path through which seats are ever taken. Two guests booking the
        last three seats at the same moment must not both succeed, and nothing
        in Python can promise that on its own: an `@api.constrains` runs against
        a snapshot that cannot see another transaction's uncommitted booking, so
        both would pass their check and both would be written.

        The order matters and each step earns its place:

        1. flush, so our own pending writes are actually in the database and the
           lock applies to the row as it really is;
        2. `FOR UPDATE`, which makes any second transaction wait here;
        3. invalidate, because the ORM cache still holds seat counts read
           *before* the lock — checking those would re-introduce exactly the
           race the lock just closed;
        4. re-read and compare.

        The caller must then write inside the same transaction, so the lock is
        still held when the seats are taken.

        `ignoring` is a booking whose currently held seats should be treated as
        free — used when an existing booking changes size, so that growing a
        party of 2 to 3 needs one more seat rather than three.
        """
        self.ensure_one()
        self.env.flush_all()
        self.env.cr.execute(
            "SELECT id FROM tour_departure WHERE id = %s FOR UPDATE", [self.id]
        )
        self.invalidate_recordset(["seats_sold", "seats_available", "state"])

        released = sum(
            booking.pax
            for booking in (ignoring or self.env["tour.booking"])
            if booking.departure_id == self and booking.state in SEAT_HOLDING_STATES
        )
        available = self.seats_available + released

        if self.state == "cancelled":
            raise UserError(_("This departure has been cancelled."))
        if self.state == "done":
            raise UserError(_("This departure has already run."))
        if not self._is_bookable():
            raise UserError(_(
                "Bookings for this departure closed %(hours)s hours before it "
                "leaves.",
                hours=self.tour_id.booking_cutoff_hours,
            ))
        if pax > available:
            raise UserError(_(
                "Only %(left)s seat(s) left on this departure, and %(asked)s "
                "were requested.",
                left=available,
                asked=pax,
            ))
        return True

    # --- Generation --------------------------------------------------------

    @api.model
    def _generate(self, rules=None, horizon_end=None):
        """Materialise departures for `rules` up to the horizon. -> recordset.

        Idempotent by construction rather than by care: a unique index on
        (tour_id, start_datetime) makes a duplicate impossible at the database
        level, and this method only ever *creates*. It never updates and never
        deletes, which is precisely why a hand-edited capacity or a manual
        cancellation survives the next run untouched.
        """
        if rules is None:
            rules = self.env["tour.availability.rule"].search([])
        horizon_end = horizon_end or (
            fields.Date.context_today(self) + relativedelta(months=HORIZON_MONTHS)
        )

        wanted = {}
        for rule in rules:
            for slot in rule._slots(horizon_end):
                # First rule to claim a slot wins. Two overlapping rules on one
                # tour describe the same 09:00 boat, not two of them.
                wanted.setdefault((slot["tour_id"], slot["start_datetime"]), slot)
        if not wanted:
            return self.browse()

        starts = [key[1] for key in wanted]
        existing = self.search([
            ("tour_id", "in", list({key[0] for key in wanted})),
            ("start_datetime", ">=", min(starts)),
            ("start_datetime", "<=", max(starts)),
        ])
        known = {(d.tour_id.id, d.start_datetime) for d in existing}

        missing = [slot for key, slot in wanted.items() if key not in known]
        return self.create(missing) if missing else self.browse()

    @api.model
    def _cron_generate_departures(self):
        """Roll the horizon forward, then tidy up behind it."""
        self._generate()
        self._retire_orphans()
        self._close_past()

    @api.model
    def _retire_orphans(self):
        """Cancel future departures whose rule no longer wants them.

        Deleting a rule, deactivating it or shrinking its date range leaves
        departures behind. They are cancelled rather than deleted, and only when
        nobody has booked and nobody has touched them by hand — silently
        removing a departure a guest has paid for is far worse than leaving a
        stale row on a calendar.
        """
        candidates = self.search([
            ("start_datetime", ">", fields.Datetime.now()),
            ("state", "in", ("draft", "open", "full")),
            ("is_manually_adjusted", "=", False),
            ("seats_sold", "=", 0),
        ])
        orphans = candidates.filtered(lambda d: not d._still_wanted())
        orphans.with_context(**{SYSTEM_WRITE: True}).write({"state": "cancelled"})
        return orphans

    def _still_wanted(self):
        """Does this departure's rule still ask for it? -> bool."""
        self.ensure_one()
        rule = self.rule_id
        if not rule or not rule.active:
            return False
        return any(
            slot["start_datetime"] == self.start_datetime
            for slot in rule._slots_for_day(self.date)
        )

    @api.model
    def _close_past(self):
        """Mark departures that have already run as done."""
        past = self.search([
            ("start_datetime", "<", fields.Datetime.now()),
            ("state", "in", ("draft", "open", "full")),
        ])
        past.with_context(**{SYSTEM_WRITE: True}).write({"state": "done"})
        return past

    # --- Manual overrides --------------------------------------------------

    def write(self, vals):
        # A person changing capacity or cancelling a departure is making a
        # decision the generator must not later undo. Flagging it here rather
        # than in the UI means it holds however the change arrives — the form,
        # a server action, a script. The module's own machinery says so with
        # SYSTEM_WRITE and is not counted.
        if not self.env.context.get(SYSTEM_WRITE) and (
            "capacity" in vals or "state" in vals
        ):
            vals = dict(vals, is_manually_adjusted=True)
        return super().write(vals)

    def action_cancel(self):
        self.write({"state": "cancelled"})
        return True

    def action_reopen(self):
        if any(d.start_datetime < fields.Datetime.now() for d in self):
            raise UserError(_("A departure that has already run cannot reopen."))
        self.write({"state": "open"})
        # A departure reopened with no seats left belongs straight back in
        # `full`, so ask rather than assume.
        self._sync_full_state()
        return True

    def action_view_bookings(self):
        self.ensure_one()
        return {
            "type": "ir.actions.act_window",
            "name": _("Bookings"),
            "res_model": "tour.booking",
            "view_mode": "list,form",
            "domain": [("departure_id", "=", self.id)],
            "context": {"default_departure_id": self.id},
        }
