from . import common
from . import test_auto_generation
from . import test_availability
from . import test_backend_ui
from . import test_booking
from . import test_calendar_grid
from . import test_cancellation
from . import test_checkout
from . import test_concurrency
from . import test_currency
from . import test_demo
from . import test_embed
from . import test_gallery
from . import test_multi_company
from . import test_embed_wizard
from . import test_page_url
from . import test_snippets
from . import test_pricing
from . import test_questions
from . import test_reaper
from . import test_website
from . import test_website_menu
